const choo = require("choo");
const html = require("nanohtml");
const devtools = require("choo-devtools");

const Toggle = require("./components/toggle");
const Door = require("./components/door");
const Turnstile = require("./components/turnstile");
const FSMRender = require("./components/fsmRender");
const FSMControls = require("./components/fsmControls");

module.exports = () => {
  const app = choo();
  const door = new Door();
  const toggle = new Toggle();
  const turnstile = new Turnstile();

  const fsm_toggle = new FSMRender(toggle);
  const fsm_turnstile = new FSMRender(turnstile);
  const fsm_door = new FSMRender(door);

  const controls_toggle = new FSMControls(toggle);
  const controls_turnstile = new FSMControls(turnstile);
  const controls_door = new FSMControls(door);

  function mainView(state, emit) {
    if (state.logger) {
      console.log("mainView:state", state);
    }
    return html`<body>
      <div style="display:flex;flex-direction:column; width:600px;">
        <h4>Interactive Display</h4>

        <div
          style="display:flex; justify-content:space-between; margin-bottom:20px;"
        >
          <div>
            ${toggle.render({ state, emit })}
            ${controls_toggle.render({ state, emit })}
          </div>
          ${fsm_toggle.render({ state, emit })}
        </div>
        <h4>Autogenerated Control set</h4>

        <div
          style="display:flex; justify-content:space-between;margin-bottom:20px;"
        >
          <div>
            ${turnstile.render({ state, emit })}
            ${controls_turnstile.render({ state, emit })}
          </div>
          ${fsm_turnstile.render({ state, emit })}
        </div>
        <h4>Guard actions + Parallel + Autogenerated Control set</h4>
        <div
          style="display:flex; justify-content:space-between;margin-bottom:20px;"
        >
          <div>
            ${door.render({ state, emit })}
            ${controls_door.render({ state, emit })}
          </div>
          ${fsm_door.render({ state, emit })}
        </div>
      </div>
    </body>`;
  }
  app.use(devtools());
  app.use((state) => {
    state.logger = false;
  });
  app.route("/", mainView);
  app.mount("body");
};
